; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_6_trillion_years_and_overnight_story=music_data_6_trillion_years_and_overnight_story
.endif

music_data_6_trillion_years_and_overnight_story:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : 6 Trillion Years and Overnight Story
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_6_trillion_years_and_overnight_story
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env5,@env1,@env0 ; 00 : Piano
	.word @env7,@env5,@env6,@env0 ; 01 : Vocal
	.word @env4,@env5,@env1,@env0 ; 02 : Piano (soft)
	.word @env3,@env5,@env6,@env0 ; 03 : Drums

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $00,$cf,$cc,$c9,$c8,$c7,$c6,$00,$06
@env3:
	.byte $00,$c4,$c4,$c2,$00,$03
@env4:
	.byte $00,$c9,$c6,$c5,$c4,$c3,$c2,$00,$06
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $00,$cc,$c9,$c7,$c6,$c5,$00,$05

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $cf, $84, $2b, $a9, $2e, $a1, $48, $89, $30, $d7, $2b, $a9, $2e, $8d, $48, $9d, $30, $d7, $30, $a5, $48, $83, $37, $ab
	.byte $35, $ab, $37, $a9, $35, $91, $48, $97, $33, $ab, $30, $d7, $48, $89, $2e, $af, $2b, $af, $29, $af, $48, $00, $af, $29
	.byte $af, $2b, $af, $29, $87, $48, $bf, $2b, $8d, $29, $8d, $27, $ad, $29, $8d, $48, $cf, $00, $cd, $48, $ff, $9f, $48, $f7
@song0ref73:
	.byte $80
@song0ref74:
	.byte $1f, $87, $22, $87, $24, $87, $27, $87
@song0ref82:
	.byte $48, $29, $91, $24, $91, $2b, $91, $24, $91, $29, $87, $2b, $87, $29, $87, $27, $87, $24, $91, $27, $91, $48, $29, $91
	.byte $24, $91, $2b, $91, $24, $91, $29, $87, $2b, $87, $29, $87, $27, $87, $22, $91, $27, $91, $48, $29, $91, $24, $91, $2b
	.byte $91, $24, $91, $29, $87, $2b, $87, $29, $87, $27, $87, $22, $91, $27, $91, $48, $29, $91, $2b, $91, $29, $87, $2b, $87
	.byte $29, $87, $27, $87, $24, $a5, $24, $91, $27, $91
	.byte $41, $29
	.word @song0ref82
@song0ref167:
	.byte $87, $2b, $87, $29, $87, $27, $87, $24, $87, $00, $87, $22, $87, $24, $87, $22, $87, $1f, $87, $1d, $87, $00, $87, $26
	.byte $87, $27, $87, $26, $87, $22, $87, $48, $1f, $87, $00, $87, $2b, $87, $2e, $87, $2b, $87, $33, $87, $30, $87, $00, $87
	.byte $82, $16, $a5, $1b, $a5, $48, $1d, $b9, $1f, $91, $1d, $b9, $1f, $91, $48, $1d, $a5, $1b, $a5, $1b, $a5, $16, $91, $1b
	.byte $91, $48, $1d, $b9, $1f, $91, $1d, $a5, $1d, $91
@song0ref249:
	.byte $1f, $91, $48, $1d, $a5, $1b, $91, $1b, $91, $1b, $a5, $00, $a5, $48, $1d, $b9, $1b, $91, $1b, $b9, $1b, $91, $48, $1d
	.byte $b9, $1b, $91, $1b, $a5, $1f, $a5, $48, $1d, $a5, $1f, $91, $1d, $b9, $1b, $91, $1b, $91, $48, $00, $cd, $16, $a5, $1b
	.byte $a5, $48, $1d, $b9, $1f, $91, $1d, $b9, $1f, $91, $48, $1d, $91, $1d, $91, $1b, $a5, $1b, $a5, $16, $91, $1b, $91, $48
	.byte $1d, $b9, $1f, $91, $1d, $b9
	.byte $41, $28
	.word @song0ref249
@song0ref330:
	.byte $1f, $a5, $22, $a5, $48, $24, $a5, $27, $91, $22, $a5, $24, $91, $1f, $a5, $48, $00, $cd, $1f, $a5, $22, $a5, $48, $1d
	.byte $a5, $1f, $91, $1d, $a5, $1b, $91, $1f, $a5, $48, $00, $cd, $1f, $a5, $22, $a5, $48, $24, $a5, $27, $a5, $22, $a5, $24
	.byte $a5, $48, $1f, $a5, $00, $a5, $1d, $a5, $1b, $a5, $48, $1d, $a5, $1f, $a5, $22, $a5, $1f, $a5, $48, $23, $a5, $00, $a5
@song0ref402:
	.byte $1f, $a5, $22, $a5
@song0ref406:
	.byte $48, $24, $a5, $1f, $91, $22, $91, $24, $9b, $24, $87, $22, $91, $1f, $91, $48, $1d, $9b, $1b, $87, $1d, $91, $1f, $91
	.byte $1b, $a5, $18, $91, $1b, $91, $48, $1d, $a5, $1d, $91, $1f, $91, $22, $91, $1f, $91, $1d, $91, $1b, $91, $48, $1d, $a5
	.byte $1d, $91, $1b, $91, $1f, $a5, $1f, $91, $22, $91, $48, $24, $a5, $1f, $91, $22, $91, $24, $a5, $24, $91, $2b, $91, $48
	.byte $29, $91, $2b, $91, $29, $91, $27, $91, $24, $a5, $24, $91, $27, $91
@song0ref492:
	.byte $48, $29, $91, $29, $87, $27, $87, $29, $91, $29, $87, $27, $87, $29, $91, $29, $87, $27, $87, $29, $91, $29, $87, $27
	.byte $87, $48, $24, $91, $27, $91, $24, $91, $22, $91, $24, $a5, $1f, $91, $22, $91
	.byte $41, $72
	.word @song0ref406
	.byte $41, $56
	.word @song0ref73
	.byte $41, $29
	.word @song0ref82
	.byte $41, $93
	.word @song0ref167
	.byte $41, $28
	.word @song0ref249
	.byte $41, $ba
	.word @song0ref330
	.byte $41, $72
	.word @song0ref406
	.byte $00, $a5, $48, $80, $50, $f0, $37, $3c, $87, $43, $30, $9b, $2b, $91, $2e, $91, $30, $9b, $30, $87, $2e, $91, $2b, $91
	.byte $48, $29, $91, $27, $91, $29, $91, $2b, $91, $24, $9b, $24, $9b, $00, $91, $48, $29, $91, $29, $a5, $2c, $91, $2b, $91
	.byte $2c, $87, $2b, $87, $29, $91, $27, $91, $48, $29, $87, $27, $87, $26, $87, $27, $87, $2b, $87, $2e, $87, $30, $87, $37
	.byte $87, $43, $35, $83, $43, $37, $85, $43, $35, $83, $43, $37, $83, $43, $35, $85, $43, $37, $83, $43, $35, $83, $43, $37
	.byte $85, $43, $35, $83, $43, $37, $83, $43, $35, $85, $43, $37, $83, $48
@song0ref663:
	.byte $2e, $83, $43, $30, $85, $43, $2e, $83, $43, $30, $83, $43, $2e, $85, $43, $30, $83, $43, $2e, $83, $43, $30, $85, $43
	.byte $2e, $83, $43, $30, $83, $43, $2e, $85, $43, $30, $83, $43
	.byte $41, $18
	.word @song0ref663
	.byte $48, $2b, $91, $29, $91, $29, $91, $2b, $91, $29, $87, $27, $87, $24, $87, $22, $87, $24, $87, $22, $87, $1f, $87, $1d
	.byte $87, $48, $1b, $87, $1d, $87, $1f, $87, $22, $87, $24, $87, $26, $87, $27, $87, $29, $87, $2b, $87, $2e, $87, $30, $87
	.byte $33, $87, $35, $87, $37, $87, $3a, $87, $3f, $87, $48, $43, $3e, $87, $43, $3f, $87, $43, $3e, $87, $43, $3f, $87, $43
	.byte $3e, $87, $43, $3f, $87, $43, $3e, $87, $43, $3f, $87, $50, $09, $4b, $30, $cd, $48, $82, $24, $b9, $27, $91, $24, $b9
	.byte $1f, $91, $48, $1d, $91, $1b, $91, $1b, $91, $1d, $91, $1f, $a5, $00, $a5, $48, $1d, $a5, $1b, $91, $1d, $91, $1d, $91
	.byte $1d, $91, $1b, $91, $1d, $91, $48, $1d, $91, $1b, $91, $1d, $a5, $1f, $a5, $00, $a5, $48, $18, $a5, $1f, $91, $1f, $91
	.byte $1d, $a5, $22, $91, $24, $91, $48, $1f, $91, $22, $91, $1d, $91, $1f, $91, $1b, $a5, $1b, $a5, $48, $1d, $a5, $1d, $91
	.byte $1f, $91, $22, $91, $1f, $91, $1d, $91, $1b, $91, $48, $1d, $a5, $1d, $91, $1b, $91, $1f, $a5, $1b, $a5, $48, $1d, $a5
	.byte $1d, $91, $1f, $91, $22, $91, $1f, $91, $1f, $91, $22, $91, $48, $23, $a5, $23, $91, $24, $91, $26, $a5, $26, $8b, $26
	.byte $89, $26, $8b, $48, $00, $cd
	.byte $41, $7a
	.word @song0ref402
	.byte $41, $76
	.word @song0ref406
	.byte $48, $24, $af, $1f, $97, $22, $99, $24, $b5, $48, $24, $a1, $2b, $a9, $29, $a9, $2b, $a1, $48, $89, $29, $af, $27, $b9
	.byte $24, $a5, $48, $ff, $9f, $48, $00, $cd, $24, $a1, $00, $81, $27, $a5
	.byte $41, $22
	.word @song0ref492
	.byte $41, $56
	.word @song0ref73
	.byte $41, $30
	.word @song0ref82
	.byte $27, $91, $2b, $91, $2e, $91, $33, $91, $48, $32, $91, $33, $91, $32, $87, $33, $87, $32, $87, $2e, $87, $2b, $a5
	.byte $41, $56
	.word @song0ref74
	.byte $41, $29
	.word @song0ref82
	.byte $41, $2e
	.word @song0ref167
	.byte $d7, $48, $29
	.byte $41, $2e
	.word @song0ref167
	.byte $d7, $48, $ff, $9f, $44, $00
@song0ch1:
@song0ref1022:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $44, $00
@song0ch2:
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $44, $00
@song0ch3:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $8b, $86, $33, $91, $ff, $9f, $a7, $00, $f5
	.byte $ff, $9f, $2e, $91, $2e, $91, $00, $f5, $2a, $91, $2a, $91, $00, $f5, $2b, $91, $2b, $91, $00, $f5, $ff, $9f, $2e, $91
	.byte $2e, $91, $00, $f5, $2a, $91, $2a, $91, $00, $f5, $2b, $87, $2b, $87, $2b, $87, $2b, $87, $2b, $87, $00, $87, $2a, $87
	.byte $2a, $87, $2a, $87, $2a, $87, $2a, $87, $00, $87, $2b, $87, $2b, $87, $2b, $87, $2b, $87, $2b, $87, $00, $87, $29, $87
	.byte $29, $87, $29, $87, $29, $87, $29, $87, $00, $d7
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $44, $00
@song0ch4:
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $41, $18
	.word @song0ref1022
	.byte $44, $00
