; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_lower_short_ver=music_data_lower_short_ver
.endif

music_data_lower_short_ver:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Lower (short ver.)
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_lower_short_ver
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env5,@env1,@env0 ; 00 : Melody
	.word @env2,@env5,@env7,@env0 ; 01 : Bass
	.word @env8,@env5,@env7,@env0 ; 02 : Instrument 1
	.word @env6,@env5,@env7,@env0 ; 03 : Noise
	.word @env4,@env5,@env7,@env0 ; 04 : Drums

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $00,$c8,$c6,$c4,$00,$03
@env3:
	.byte $00,$cf,$cc,$c9,$c8,$c7,$c6,$00,$06
@env4:
	.byte $00,$c4,$c4,$c2,$00,$03
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$c4,$7f,$00,$02
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $00,$c2,$c1,$05,$c0,$00,$04

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $b3, $80, $1a, $b9
@song0ref10:
	.byte $48, $1f, $b9, $1f, $b9, $1f, $9b, $1f, $9b, $1f, $9b, $1d, $9b, $48, $1f, $ab, $00, $8b, $1f, $b9, $1f, $9b, $20, $9b
	.byte $1f, $9b, $1d, $9b
	.byte $41, $1a
	.word @song0ref10
	.byte $41, $1a
	.word @song0ref10
	.byte $48, $1f, $b9, $1f, $b9, $1f, $9b, $1d, $9b, $1f, $9b, $1d, $9b, $48, $1f, $9b, $20, $8d, $00, $8b, $1f, $9b, $1d, $9b
	.byte $18, $ab, $00, $a9, $1a
@song0ref73:
	.byte $9b, $48, $21, $9b, $24, $9b, $26, $ab, $1f, $9b, $1f, $9b, $1d, $8b, $1f, $9b, $26, $8d, $25, $8b, $48, $26, $8d, $20
	.byte $8b, $21, $8d, $1d, $8b, $1c, $8d, $24, $8b, $23, $8d, $22, $8b, $21, $8d, $1f, $9b, $21, $8b, $20, $8d, $21, $8b, $21
	.byte $41, $2e
	.word @song0ref73
	.byte $41, $2e
	.word @song0ref73
	.byte $41, $2d
	.word @song0ref73
@song0ref130:
	.byte $1d, $9b
@song0ref132:
	.byte $48, $1f, $9b, $1f, $9b, $1f, $9b, $1d, $9b, $1f, $8d, $1d, $8b, $1f, $8d, $21, $9b, $1d, $8b, $1f, $8d, $1d, $8b
	.byte $41, $16
	.word @song0ref132
	.byte $41, $16
	.word @song0ref132
	.byte $48, $9d, $00, $ff, $a3, $1d, $8b, $1f, $8d, $1d, $8b
	.byte $41, $16
	.word @song0ref132
	.byte $41, $16
	.word @song0ref132
	.byte $41, $16
	.word @song0ref132
	.byte $48, $26, $9b
@song0ref184:
	.byte $29, $8d, $45, $8b, $29, $8d, $45, $8b, $29, $8d, $45, $8b
	.byte $41, $0c
	.word @song0ref184
	.byte $41, $18
	.word @song0ref130
	.byte $41, $16
	.word @song0ref132
	.byte $41, $16
	.word @song0ref132
	.byte $48, $25, $8d, $26, $8b, $20, $8d, $21, $8b, $1d, $8d, $1f, $8b, $19, $8d, $1a, $8b, $16, $8d, $14, $8b, $15, $9b, $00
	.byte $8d, $1d, $8b, $1f, $8d, $1d, $8b
	.byte $41, $16
	.word @song0ref132
	.byte $41, $16
	.word @song0ref132
	.byte $41, $16
	.word @song0ref132
	.byte $48, $00, $b9, $1a, $9b, $1d, $9b, $1f, $9b, $1d, $9b, $1f
@song0ref260:
	.byte $9b, $21, $9b, $48, $26, $9b, $00, $9b, $21, $9b, $00, $9b, $1f, $8d, $1d, $9b, $21, $9b, $26, $9b, $24, $8b, $48, $9d
	.byte $24, $9b, $24, $8d, $22, $9b, $21, $b9, $00, $8b, $1d, $8d, $1f, $8b, $1f, $8d, $21, $8b, $48, $9d, $1d, $9b, $1d, $8d
	.byte $1f, $9b, $21, $a9, $1d, $9b, $1d, $8d, $1f, $9b, $21, $8b, $48, $9d, $00, $b9, $26, $9b, $24, $9b, $21, $9b, $20
	.byte $41, $1d
	.word @song0ref260
	.byte $c7, $21, $8d, $20, $8b, $1f, $8d, $1d, $8b, $48, $1f, $9b, $1d, $9b, $1f, $9b, $1d, $8d, $1f, $9b, $1d, $8b, $1f, $8d
	.byte $1d, $8b, $1f, $9b, $22, $9b, $48, $21, $9b, $00, $d7
@song0ref369:
	.byte $21, $8d, $23, $9b
@song0ref373:
	.byte $26, $9b, $28, $8b, $26, $8d, $28, $8b, $48, $2a, $9b, $29, $9b, $28, $9b, $26, $9b, $00, $9b, $23, $8d
	.byte $41, $14
	.word @song0ref373
	.byte $41, $0a
	.word @song0ref373
	.byte $26, $9b, $23, $9b, $2a, $8d, $28, $a9, $25, $9b, $22, $9b, $2b, $9b, $48, $2b, $ab, $2a, $a9, $00, $9b
	.byte $41, $18
	.word @song0ref369
	.byte $41, $0a
	.word @song0ref373
	.byte $2e, $9b, $28, $9b, $26, $9b, $00, $9b, $29, $9b, $28
@song0ref438:
	.byte $9b, $28, $9b, $48, $9d, $29, $9b, $28, $9b, $29, $9b, $28, $9b, $26, $9b, $23
	.byte $41, $0e
	.word @song0ref438
	.byte $21, $9b, $22
@song0ref460:
	.byte $9b, $48, $1e, $9b, $21, $9b, $23, $ab, $1c, $8b, $00, $8d, $1c, $9b, $1a, $8b, $1c, $9b, $23, $8d, $21, $8b, $48, $23
	.byte $8d, $1d, $8b, $1e, $8d, $1a, $8b, $19, $8d, $21, $8b, $20, $8d, $1f, $8b, $1e, $8d, $1c, $9b, $1e, $8b, $1d, $8d, $1e
	.byte $8b, $1e
	.byte $41, $30
	.word @song0ref460
	.byte $41, $30
	.word @song0ref460
	.byte $41, $30
	.word @song0ref460
	.byte $9b, $48, $17, $b9, $00, $ff, $b1, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ef, $80
@song0ref533:
	.byte $1a, $b9, $19, $b9, $1a, $9b, $1a, $9b, $1a, $9b, $19, $9b, $1a, $ab, $00, $8b, $19, $b9, $1a, $9b, $1a, $9b, $1a, $9b
	.byte $00, $9b
	.byte $41, $1a
	.word @song0ref533
	.byte $41, $1a
	.word @song0ref533
	.byte $1a, $b9, $19, $b9, $1a, $9b, $00, $d7, $1a, $9b, $00, $d7, $11, $ab, $00, $c7
@song0ref581:
	.byte $1a, $9b, $00, $9b, $20, $ab, $19, $9b, $19, $9b, $00, $a9, $1d, $8d, $00, $8b, $f7, $1c, $8d, $00, $9b, $1d, $8b, $00
	.byte $9b, $1d, $9b
	.byte $41, $1b
	.word @song0ref581
	.byte $41, $1b
	.word @song0ref581
	.byte $41, $10
	.word @song0ref581
	.byte $ff, $ef
@song0ref619:
	.byte $82
@song0ref620:
	.byte $1a, $9b, $00, $9b, $19, $9b, $00, $9b, $18, $ab, $17, $8b, $00, $b9
	.byte $41, $0e
	.word @song0ref620
	.byte $41, $0e
	.word @song0ref620
	.byte $ff, $ef
	.byte $41, $0e
	.word @song0ref620
	.byte $41, $0e
	.word @song0ref620
	.byte $41, $0e
	.word @song0ref620
	.byte $9d, $80
@song0ref653:
	.byte $26, $8d, $45, $8b, $26, $8d, $45, $8b, $26, $8d, $45, $8b
	.byte $41, $09
	.word @song0ref653
	.byte $93, $45, $95, $00, $8b
	.byte $41, $0e
	.word @song0ref619
	.byte $41, $0e
	.word @song0ref620
	.byte $41, $0e
	.word @song0ref620
	.byte $ff, $ef
	.byte $41, $0e
	.word @song0ref620
	.byte $41, $0e
	.word @song0ref620
	.byte $41, $0e
	.word @song0ref620
	.byte $ff, $ef, $80
@song0ref696:
	.byte $1d, $ab, $00, $8b, $1d, $ab, $00, $f5, $21, $8b, $9d, $21, $9b, $1d, $8d, $00, $9b, $1d, $b9, $00, $b9, $1d, $8b, $9d
	.byte $00, $c9, $19, $a9, $00, $c9, $1a, $8b, $9d, $00, $b9, $1d, $9b, $00, $f5
	.byte $41, $0d
	.word @song0ref696
	.byte $21, $8d, $00, $9b, $1d, $c7, $1a, $8d, $00, $a9, $1a, $9b, $00, $9b, $1a, $9b, $00, $8d, $1a, $9b, $00, $e5, $1c, $9b
	.byte $00, $ff, $85, $1a, $9b, $00, $9b, $1c, $8b
@song0ref771:
	.byte $26, $9b, $23, $9b, $1c, $9b, $1a, $9b, $00, $f5
	.byte $41, $0a
	.word @song0ref771
	.byte $26, $9b, $1a, $9b, $17, $9b, $1e, $8d, $25, $a9, $00, $b9, $1f, $9b, $26, $ab, $26, $a9, $00, $ff, $93
	.byte $41, $0a
	.word @song0ref771
	.byte $26, $9b, $22, $9b, $1c, $9b, $1a, $9b, $00, $d7
@song0ref818:
	.byte $23, $9b, $9d, $00, $9b, $23, $9b, $00, $9b, $1c, $9b, $00, $9b, $17, $9b
	.byte $41, $0c
	.word @song0ref818
	.byte $d7
@song0ref837:
	.byte $17, $9b, $00, $9b, $1a, $ab, $15, $8b, $00, $8d, $15, $9b, $00, $a9, $1c, $8d, $00, $8b, $1c, $8d, $00, $a9, $12, $8d
	.byte $00, $a9, $19, $8d, $00, $c7, $17, $9b
	.byte $41, $20
	.word @song0ref837
	.byte $41, $20
	.word @song0ref837
	.byte $41, $20
	.word @song0ref837
	.byte $0b, $b9, $00, $ff, $b1, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref887:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $f7, $84, $0c, $9b, $02, $9b, $02, $9b
	.byte $02
@song0ref912:
	.byte $9b
@song0ref913:
	.byte $00, $9b, $07, $9b, $00, $9b, $07, $9b, $00, $9b, $09, $9b, $00, $9b, $09, $9b, $40, $0a, $9b, $0a, $9b, $00, $9b, $09
	.byte $9b, $02, $9b, $0e, $9b, $02, $9b, $0e
	.byte $41, $20
	.word @song0ref912
	.byte $41, $20
	.word @song0ref912
	.byte $41, $11
	.word @song0ref912
	.byte $0a, $b9, $0a, $b9, $10, $b9, $09, $9b, $00, $9b
@song0ref964:
	.byte $0e, $9b, $1a, $9b, $0d, $9b, $19, $9b, $0a, $9b, $16, $9b, $0a, $8d, $16, $8b, $0a, $8d, $00, $8b
	.byte $41, $14
	.word @song0ref964
	.byte $41, $14
	.word @song0ref964
	.byte $ff, $ef
	.byte $41, $14
	.word @song0ref964
	.byte $41, $14
	.word @song0ref964
	.byte $41, $14
	.word @song0ref964
	.byte $ff, $ef
	.byte $41, $14
	.word @song0ref964
	.byte $41, $14
	.word @song0ref964
	.byte $41, $14
	.word @song0ref964
	.byte $ff, $ef
	.byte $41, $14
	.word @song0ref964
	.byte $41, $14
	.word @song0ref964
	.byte $41, $14
	.word @song0ref964
	.byte $ff, $ef
@song0ref1025:
	.byte $0a, $9b, $00, $9b, $11, $9b, $00, $9b, $0c, $9b, $00, $9b, $13, $9b, $00, $9b, $0d, $9b, $00, $9b, $08, $9b, $00, $9b
	.byte $0d, $9b, $00, $9b, $08, $9b, $00, $9b
	.byte $41, $20
	.word @song0ref1025
	.byte $41, $20
	.word @song0ref1025
	.byte $03, $9b, $00, $9b, $03, $9b, $00, $9b, $03, $9b, $0d, $9b, $0a, $9b, $07, $9b, $00, $ff, $ed
@song0ref1082:
	.byte $07, $9b, $13, $9b, $07, $9b, $13, $9b, $09, $9b, $15, $9b, $09, $9b, $15, $9b, $0b, $9b, $17, $9b, $0b, $9b, $17, $9b
	.byte $0b, $9b, $17, $9b, $0b, $9b, $17, $9b, $07, $9b, $13, $9b, $07, $9b, $13, $9b, $06, $9b, $12, $9b, $06, $9b, $12, $9b
	.byte $0b, $9b, $17, $9b, $0d, $9b, $19, $9b, $0b, $8d, $13, $9b, $12, $9b, $00, $a9
	.byte $41, $10
	.word @song0ref1082
	.byte $06, $9b, $12, $9b, $06, $9b, $12, $9b, $17, $9b, $12, $9b, $17, $9b, $10, $9b, $9d, $00, $9b, $17, $9b, $17, $9b, $15
	.byte $9b, $12, $9b, $00, $9b, $13, $9b, $9d, $17, $9b, $17, $9b, $15, $9b, $15, $9b, $00, $d7
	.byte $41, $10
	.word @song0ref913
@song0ref1194:
	.byte $00, $9b, $06, $9b, $00, $9b, $06, $9b, $00, $9b, $0b, $9b, $00, $9b, $0b
	.byte $41, $11
	.word @song0ref912
	.byte $41, $0f
	.word @song0ref1194
	.byte $41, $11
	.word @song0ref912
	.byte $41, $0f
	.word @song0ref1194
	.byte $41, $11
	.word @song0ref912
	.byte $07, $ab, $00, $8b, $06, $b9, $0d, $b9, $06, $ab, $00, $8b, $80, $40, $0b, $b9, $00, $ff, $b1, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $ef, $ff, $ef, $ff, $d1, $86, $23, $9b, $00, $ff, $ed, $ff, $d1, $28, $9b, $00, $ff, $ed, $ff, $d1, $27, $9b, $00
	.byte $ff, $ed, $2f, $ab, $00, $8b, $2f, $ab, $00, $ff, $83, $88
@song0ref1283:
	.byte $07, $8d, $00, $8b, $1e, $8d, $00, $8b, $07, $8d, $00, $8b, $1e, $8d, $00, $8b
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $28, $b9, $00, $ff, $b1
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $41, $10
	.word @song0ref1283
	.byte $17, $d7, $00, $ff, $93, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $10
	.word @song0ref887
	.byte $41, $10
	.word @song0ref887
	.byte $41, $10
	.word @song0ref887
	.byte $41, $10
	.word @song0ref887
	.byte $41, $10
	.word @song0ref887
	.byte $41, $10
	.word @song0ref887
	.byte $41, $10
	.word @song0ref887
	.byte $ff, $ef, $ff, $ef, $42
	.word @song0ch4loop
