; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_lower=music_data_lower
.endif

music_data_lower:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Lower
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_lower
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env3,@env1,@env0 ; 00 : Melody
	.word @env5,@env3,@env6,@env0 ; 01 : Noise
	.word @env2,@env3,@env6,@env0 ; 02 : Drums

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $00,$c4,$c4,$c2,$00,$03
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $00,$ca,$c8,$c6,$c4,$c2,$c1,$00,$06
@env5:
	.byte $00,$c4,$7f,$00,$02
@env6:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $b3, $80, $1a, $b9
@song0ref10:
	.byte $48, $1f, $b9, $1f, $b9, $1f, $9b, $1f, $9b, $1f, $9b, $1d, $9b, $48, $1f, $ab, $00, $8b, $1f, $b9, $1f, $9b, $20, $9b
	.byte $1f, $9b, $1d, $9b
	.byte $41, $1a
	.word @song0ref10
	.byte $41, $1a
	.word @song0ref10
	.byte $48, $1f, $b9, $1f, $b9, $1f, $9b, $1d, $9b, $1f, $9b, $1d, $9b, $48, $1f, $9b, $20, $8d, $00, $8b, $1f, $9b, $1d, $9b
	.byte $18, $ab, $00, $a9, $1a
@song0ref73:
	.byte $9b, $48, $21, $9b, $24, $9b, $26, $ab, $1f, $9b, $1f, $9b, $1d, $8b, $1f, $9b, $26, $8d, $25, $8b, $48, $26, $8d, $20
	.byte $8b, $21, $8d, $1d, $8b, $1c, $8d, $24, $8b, $23, $8d, $22, $8b, $21, $8d, $1f, $9b, $21, $8b, $20, $8d, $21, $8b, $21
	.byte $41, $2e
	.word @song0ref73
	.byte $41, $2e
	.word @song0ref73
	.byte $41, $2d
	.word @song0ref73
@song0ref130:
	.byte $1d, $9b, $48, $1f, $9b, $1f, $9b, $1f, $9b, $1d, $9b, $1f, $8d, $1d, $8b, $1f, $8d, $21, $9b
@song0ref149:
	.byte $1d, $8b, $1f, $8d, $1d, $8b, $48, $1f, $9b, $1f, $9b, $1f, $9b, $1d, $9b, $1f, $8d, $1d, $8b, $1f, $8d, $21, $9b, $1d
	.byte $8b, $1f, $8d, $1d, $8b, $48, $1f, $9b, $1f, $9b, $1f, $9b, $1d, $9b, $1f, $8d, $1d, $8b, $1f, $8d, $21, $9b, $1d, $8b
	.byte $1f, $8d, $1d, $8b, $48, $9d, $00, $ff, $a3
	.byte $41, $32
	.word @song0ref149
	.byte $48, $1f, $9b, $1f, $9b, $1f, $9b, $1d, $9b, $1f, $8d, $1d, $8b, $1f, $8d, $21, $9b, $1d, $8b, $1f, $8d, $1d, $8b, $48
	.byte $26, $9b, $29, $9b, $29, $9b, $29, $9b, $29, $9b, $29, $9b, $29, $9b
	.byte $41, $44
	.word @song0ref130
	.byte $48, $25, $8d, $26, $8b, $20, $8d, $21, $8b, $1d, $8d, $1f, $8b, $19, $8d, $1a, $8b, $16, $8d, $14, $8b, $15, $9b, $00
	.byte $8d
	.byte $41, $32
	.word @song0ref149
	.byte $48, $1f, $9b, $1f, $9b, $1f, $9b, $1d, $9b, $1f, $8d, $1d, $8b, $1f, $8d, $21, $9b, $1d, $8b, $1f, $8d, $1d, $8b, $48
	.byte $00, $b9, $1a, $9b, $1d, $9b, $1f, $9b, $1d, $9b, $1f
@song0ref313:
	.byte $9b, $21, $9b, $48, $26, $ab, $00, $8b, $21, $ab, $00, $8b, $1f, $8d, $1d, $9b, $21, $9b, $26, $9b, $24, $8b, $48, $9d
	.byte $24, $9b, $24, $8d, $22, $9b, $21, $b9, $00, $8b, $1d, $8d, $1f, $8b, $1f, $8d, $21, $8b, $48, $9d, $1d, $9b, $1d, $8d
	.byte $1f, $9b, $21, $a9, $1d, $9b, $1d, $8d, $1f, $9b, $21, $8b, $48, $9d, $00, $b9, $26, $9b, $24, $9b, $21, $9b, $20
	.byte $41, $1d
	.word @song0ref313
	.byte $c7, $21, $8d, $20, $8b, $1f, $8d, $1d, $8b, $48, $1f, $9b, $1d, $9b, $1f, $9b, $1d, $8d, $1f, $9b, $1d, $8b, $1f, $8d
	.byte $1d, $8b, $1f, $9b, $22, $9b, $48, $21, $9b, $00, $d7, $21, $8d, $23, $9b, $26, $9b, $28, $8b, $26, $8d, $28, $8b, $48
	.byte $2a, $9b, $29, $9b, $28, $9b, $26, $9b, $00, $f5, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff
	.byte $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff
	.byte $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff
	.byte $ef, $48, $ff, $ef, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ef, $80
@song0ref518:
	.byte $1a, $b9, $19, $b9, $1a, $9b, $1a, $9b, $1a, $9b, $19, $9b, $1a, $ab, $00, $8b, $19, $b9, $1a, $9b, $1a, $9b, $1a, $9b
	.byte $00, $9b
	.byte $41, $1a
	.word @song0ref518
	.byte $41, $1a
	.word @song0ref518
	.byte $1a, $b9, $19, $b9, $1a, $9b, $00, $d7, $1a, $9b, $00, $d7, $11, $ab, $00, $c7
@song0ref566:
	.byte $1a, $9b, $00, $9b, $20, $ab, $19, $9b, $19, $9b, $00, $a9, $1d, $8d, $00, $8b, $f7, $1c, $8d, $00, $9b, $1d, $8b, $00
	.byte $9b, $1d, $9b
	.byte $41, $1b
	.word @song0ref566
	.byte $41, $1b
	.word @song0ref566
	.byte $1a, $9b, $00, $9b, $20, $ab, $19, $9b, $19, $9b, $00, $a9, $1d, $8d, $00, $8b
@song0ref615:
	.byte $ff, $ef
@song0ref617:
	.byte $1a, $9b, $00, $9b, $19, $9b, $00, $9b, $18, $ab, $17, $8b, $00, $b9, $1a, $9b, $00, $9b, $19, $9b, $00, $9b, $18, $ab
	.byte $17, $8b, $00, $b9, $1a, $9b, $00, $9b, $19, $9b, $00, $9b, $18, $ab, $17, $8b, $00, $b9
	.byte $41, $2c
	.word @song0ref615
	.byte $9d, $26, $9b, $26, $9b, $26, $9b, $26, $9b, $26, $9b, $26, $ab, $00, $8b
	.byte $41, $2a
	.word @song0ref617
	.byte $41, $2c
	.word @song0ref615
	.byte $ff, $ef, $1d, $ab, $00, $8b, $1d, $ab, $00, $f5, $21, $8b, $9d, $21, $9b, $1d, $8d, $00, $9b, $1d, $b9, $00, $b9, $1d
	.byte $8b, $9d, $00, $c9, $19, $a9, $00, $c9, $1a, $8b, $9d, $00, $b9, $1d, $9b, $00, $f5, $1d, $ab, $00, $8b, $1d, $ab, $00
	.byte $f5, $21, $8b, $9d, $21, $9b, $21, $8d, $00, $9b, $1d, $c7, $1a, $8d, $00, $a9, $1a, $9b, $00, $9b, $1a, $9b, $00, $8d
	.byte $1a, $9b, $00, $e5, $1c, $9b, $00, $ff, $85, $1a, $9b, $00, $9b, $1c, $8b, $1e, $9b, $1d, $9b, $1c, $9b, $1a, $9b, $00
	.byte $f5
@song0ref780:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $2c
	.word @song0ref780
	.byte $41, $2c
	.word @song0ref780
	.byte $41, $28
	.word @song0ref780
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $ef, $ff, $ef, $ff, $d1, $82, $23, $9b, $00, $ff, $ed, $ff, $d1, $28, $9b, $00, $ff, $ed, $ff, $d1, $27, $9b, $00
	.byte $ff, $ed, $2f, $ab, $00, $8b, $2f, $ab, $00, $ff, $83, $84
@song0ref877:
	.byte $07, $8d, $00, $8b, $1e, $8d, $00, $8b, $07, $8d, $00, $8b, $1e, $8d, $00, $8b, $07, $8d, $00, $8b, $1e, $8d, $00, $8b
	.byte $07, $8d, $00, $8b, $1e, $8d, $00, $8b
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $41, $20
	.word @song0ref877
	.byte $ff, $ef
	.byte $41, $20
	.word @song0ref877
	.byte $41, $2c
	.word @song0ref780
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $2c
	.word @song0ref780
	.byte $41, $2c
	.word @song0ref780
	.byte $41, $28
	.word @song0ref780
	.byte $42
	.word @song0ch4loop
